### ISSUE TITLE
宣称比 fastfetch 还快的 fetch 隔三差五就会冒出一个

### ISSUE THREAD

**Issue by CarterLi** [charleschetty/ccfetch#4]
然后去 r/unixporn 一看，发现自己的对手还是 neofetch 😆

**Comment by CarterLi** [comment]
Checklist:

1. 嵌套 shell，比如在 bash 里 exec zsh，检查 shell 是否正确
2. 中间程序。比如 `sudo *fetch`，检查 terminal 是否正确
3. 在桌面配置里手工改低分辨率，检查分辨率正确
4. 另外缺失的功能，刷新率，shell版本号等，你慢慢加好了再和fastfetch比速度

**Comment by charleschetty** [comment]
你这刷github真勤啊，我昨天刚发出来你这就看着了

感谢帮忙找出问题，这几个问题马上修，版本号，刷新率这种功能可能会加，不过再看吧，因为这两个对我来说没什么感知。

这项目本来是我自己写着玩的，结果写出来意外发现比fastfetch快，然后就贴了个benchmark。

兼容性，i/o，处理版本号什么自然都是需要花时间，像我这种没怎么处理的自然要快一些。

我是没想到这项目能把你炸出来，anyway，感谢帮忙找出问题。

**Comment by CarterLi** [comment]
> 因为这两个对我来说没什么感知

那要你这么说，我对除shell名字之外所有东西都没感知。我拿 `echo $SHELL` 和你比速度怎么样？

**Comment by charleschetty** [comment]
你何必火气这么大，

另外我实验了一下，在我电脑上，去掉fastfetch的shell,monitor,terminal，速度在12ms左右，我这个还是快一些，但快自然是有代价的，正如我前面说了，兼容性，i/o，处理版本号会花不少时间，我总共代码不一定有你两三个功能代码多，这些东西处理的十分简陋，而且没有提供用户配置，所消耗的时间自然会少一些。

不过你也指出了，我的benchmark的确不严谨，这是我的问题。

**Comment by CarterLi** [comment]
你的程序所有东西都静态编译进去了。而fastfetch所有样式都是配置在配置文件里的。首先要解析命令行参数找到配置文件地址，然后把配置文件读进内存，然后把字符串解析成JSON对象，然后递归遍历JSON对象把值填充到fastfetch内部的数据结构里，然后把动态变量 `{$1}` `{#1}` 做运行时替换。。。我估计光折腾一个配置文件几毫秒就出去了。。。
